Fix unit test failure due to IllegalAccessError
java.lang.IllegalAccessError: Class ref in pre-verified class resolved
to unexpected implementation because of latinime-common reference added
two times.

Change-Id: I4ce1185c10b9a217022e830b02aec4f1ea50f2eb