Simplify CursorAnchorInfoCompatWrapper
With this CL, we will use CursorAnchorInfoCompatWrapper just to
avoid unexpected NoClassDefFoundError due to the direct
dependency CursorAnchorInfo class, which is available only on
API level 21 and later.

Change-Id: I254ff83f1ca41daa21d0666b5824af22ba529022